language: ruby
cache:
- bundler: true
- directories:
  - "/home/travis/.phantomjs"
before_script:
- createdb test_vgbot
- bundle exec rake db:migrate
script:
- bundle exec rake spec
- export DISPLAY=:99.0 && bundle exec rake jasmine:ci[random]
env:
  global:
  - RAILS_ENV: test
    TRAVIS: true
addons:
  postgresql: 9.3
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: Qi5dAMgUXKTnUqZoBTQuKvGQRZ7pA7EqsfS0kVsjBHUqrQN2b4thuUc6FE9NwQk0kSgVQIscocr+8uEPG9UrWBydpjxveP3/HV5V9qznnUhgUiKTVyEX98Y56bF5B7hWWQN8AZsTUYWQBMxiV75yJIV+WvEEmL/64tick91xnYU4yiCSyuEneq9LFPU7IRrn9AvPjT005SvD6xkshUuhV9NEyrB7wFBAhtpXQ0tp5aZQUl4/rbxLELAr3nrPydi9Bv5X+RRP0g8JD8Zb2M0v3jQ1BEgtg8Qn+FrBtsUiAFZDz/5t+1/zWMmw29qGA6CrzVYpPeH8EhPF7DS+LhQ32PzbHvRL6c4xeqL6/e+s5zOY3cPENK+FloPh2tA0FVJTfZYIa6IWp79+h8jofsXr+a9CCaEGWup+mzbdvyli61ajNBbc3XswJz3mTF9Vz3Iro09lCiWihF7XVjxApHgSkDe2CM2fwiJ+Au+mn56oEveBqTvCIVh6pC8Utifi9ifpzkt9xox3uWPzzbia57fPf18g8WC/w7EEOuYGzmV5w2+8NVgT5/NzxueLjDA2zDybcasGtiBxfTrkL4pCtBt+tKTLD9Ny73VvHZWf60Yfywf5LxpLpMFOM05fGfyORfdHArNc1VoT5q/hTy1JYLgEZFyPmDfbeqHMUJjLnzl5+Gw=
  app: voterguidebot
  run:
  - rake db:migrate
  - bundle exec rake render:assets
  on:
    repo: mojowen/voterguidebot
