language: ruby
cache:
- bundler: true
- directories:
  - "/home/travis/.phantomjs"
before_script:
- createdb test_vgbot
- bundle exec rake db:migrate
script:
- bundle exec rake spec
- export DISPLAY=:99.0 && bundle exec rake jasmine:ci[random]
env:
  global:
  - RAILS_ENV: test
    TRAVIS: true
addons:
  postgresql: 9.3
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: hdPzyziKxFMkLg9K0DXfxpvH/EoeBRg9tCYK1jrPvy9uZUrQfEoj+vpOkp8uMDTON5x2wbnBNkooxdNjFJzVm/CBNBOJOX0n/MkFM41yFTHRvolCM5nAAZyc04vthJHAPSzKC6pfCWAEAiFZAQdfrcmIlwYkqvNwbYXf0gzka0nj5+Seklwykqn7geErhM5kH/iYyALXbxKvqak2a/S6xD5kI9c6n9nOdr/APbHKWdOYjhgDZhZbX0x2rrWfTL0fNTdz/RtZcYfBvAoWzBA4rgvz1t9Y9PxUEdP4PvF3JqbX9Q2PBIHYJ1Ttjd6e8CR7YrFxMZktAfvLTeFa93YoU6qOzugIgSripnEH/qk/BK5OuTuxuspYXgd3NG2WxwPj0vNg6YO9Bs5FjV1j16aza5YjQiaBxfaU9zrrAfVIlPjQ9XD3v5IAsoxribVcER37m8D66Gknu94jLkqW9+w/FWBeVjF+Hk7ktAYw1uO6G07hmdV8VcLHjDdnp0yHHrFQ6Ij56Sw8kR8WND1ksgh3TYTycKMddeTwDzSWuS4mCI4CvAdICMk88kPg0hJr0GQSOkUbyfkdhO2bQN55mkVizoh5Y8mAiG0HuLJYHbNBrIfnGU4Ni9xiskNmsJU2p262GI8/GGnol3sOTyMpl42MegpCu0w1hGeTKEHSEDIZAi8=
  app: voterguidebot
  run:
  - rake db:migrate
  - bundle exec rake render:assets
  on:
    repo: mojowen/voterguidebot
